### ISSUE TITLE
support a way using custom icons

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-icons#1]
Import https://www.npmjs.com/package/dynamic-icon

**Comment by HeskeyBaozi** [comment]
`dynamic-icon`自定义图标的本质是`iconfont.cn`上托管的字体图标的自定义。
我的思路是在`Icon`组件上新增静态方法`createCustom`，并引用自`DynamicIcon.create({...})`。

但现在大多数自定义图标的情况是下列两种：
1. 用户在自己本地环境拥有`.ttf`/`.eot`字体文件，需要自己引入`css`文件。这种做法实际上和以前完全一致。
2. 用户自己拥有图标文件（`.svg`）。用户需要自己将`svg`标签转换成`jsx`，如：
```jsx
const HomeIcon = (props) => (
  <svg {...props}>
    <path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z" />
  </svg>
);

render(<HomeIcon />, mountedNode);
```
此库本质上也是一个导出由`svg`转换成`react component`的“静态”库。类似于[Material Icons](https://material.io/tools/icons/?icon=attach_money&style=baseline)。

但是最终我觉得还是无法令人满意。目标是向后兼容字体图标、且用户的自定义图标也可以使用。

**Comment by afc163** [comment]
1. 大多数用户的需求都是用 iconfont.cn，也是我们推荐的方案：https://pro.ant.design/docs/biz-icon-cn
2. 本地环境 tff eot svg，提供文档帮助即可，目前不太可能提供傻瓜式的方案。
