### ISSUE TITLE
Login icon: Is the direction of the arrow wrong?

### ISSUE THREAD

**Issue by macbesu** [ant-design/ant-design-icons#11]
I am curious about it.

Old version ( <= v3.6.3 ):
https://2x.ant.design/components/icon
![image](https://user-images.githubusercontent.com/16490377/45131655-86e82c80-b1c0-11e8-89ee-414e85d834e4.png)

New version ( v3.9.1 ):
https://ant.design/components/icon
https://github.com/ant-design/ant-design-icons/blob/master/svg/outline/login.svg

![image](https://user-images.githubusercontent.com/16490377/45131352-32907d00-b1bf-11e8-93f6-8b9d9b8f099b.png)

**Comment by HeskeyBaozi** [comment]
~~This is by design~~
Sorry, That's my fault. It will be fixed in the next patch version.
![image](https://user-images.githubusercontent.com/15819224/45137777-a7be7b00-b1dc-11e8-9bbb-40f4478ac67d.png)

**Comment by macbesu** [comment]
Got it. Thanks :)

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12114
