### ISSUE TITLE
angular: icon dynamic loading with jsonp-like tech

### ISSUE THREAD

**Issue by wzhudev** [ant-design/ant-design-icons#110]
Now icons-angular provide dynamic loading which enable users to load icon resource through `XMLRequest` (in order to reduce bundling size). However, most CDN don't support cross-domain `XMLRequest`. 

A jsonp like tech is required. When translating icon resources, instead of omitting svg files, we omit js files like:

```js
(function() {
  window.__ant_load_icon(
    /** icon definition goes here */
  );
})();
```

So, when icons-angular tries to load an icon dynamically, instead of firing a `XMLRequest`, it inserts a script into DOM like:

```html
<script src="https://yourcdngoeshere.com/icons/outline/smile.js"></script>
```

**Comment by wendzhue** [comment]
I will continue this work after refactoring to the dependent is done.
