### ISSUE TITLE
How to use it as external in webpack?

### ISSUE THREAD

**Issue by iugo** [ant-design/ant-design-icons#14]
I use antd as external in webpack. When antd version to v3.9.x, the main bundle size be added 700+kb.

Through webpack-bundle-analyzer, I found that the bundle grows caused by @ant-design/icons.

Want use the https://unpkg.com/@ant-design/icons@1.0.3 CDN.

**Comment by HeskeyBaozi** [comment]
Use `umd.js` in https://unpkg.com/@ant-design/icons@next/lib/
it export all icons as variable `AntDesignIcons`.

# Notice
it is not released, use it in `antd@3.9.2` or later. `antd@3.9.1` doesn't work

**Comment by iugo** [comment]
@HeskeyBaozi antd@3.10.0 doesn't work.

```
webpack.externals: {
  antd: 'antd',
  bizcharts: 'BizCharts',
  '@ant-design/icons': 'AntDesignIcons',
},
```

According to BundleAnalyzerPlugin analysis, '@ant-design/icons' still be packaged.

**Comment by ZhenlyChen** [comment]
I had a same problem.
How to use externals instead of '@ant-design/icons

**Comment by iifksp** [comment]
遇到同样的问题，就算只用一个Input，即使在wepack externals设置了antd，也会一下就把icon都打包进来了。

**Comment by sushree-yai** [comment]
How was this resolved? Can someone help pls? I am on antd 4 and creating a component library out of antd. Even if I add it to externals in webpack, I am still seeing a lot of related code in bundle like antdesign icons and rc- stuff. Can someone help pls @afc163
