### ISSUE TITLE
这个写法是有问题的吧？这样不是必定 js 么？ useJsonpLoading 是个方法

### ISSUE THREAD

**Issue by olivewind** [ant-design/ant-design-icons#148]
这个写法是有问题的吧？这样不是必定 js 么？ useJsonpLoading 是个方法

![image](https://user-images.githubusercontent.com/17901361/67089862-36bd0580-f1db-11e9-95ac-5e8f913082da.png)

_Originally posted by @olivewind in https://github.com/ant-design/ant-design-icons/diffs_

**Comment by wzhudev** [comment]
这个问题已经在最新的版本中修复。
