### ISSUE TITLE
Support pass spin to icons

### ISSUE THREAD

**Issue by mrquokka** [ant-design/ant-design-icons#150]
Hi, i tried to use loading icon, but cannot make it animated
expected result
```
<antd-icon :type="icon_type"
  :class="current_state"
  sync
  v-on:click="get_changes" />
```
But it is not work, and pass 'sync' to class and type does not help

**Comment by tangjinzhou** [comment]
You need to write your own css animation.
ant-design-icons does not contain styles.

**Comment by tangjinzhou** [comment]
Please use the icon component in [ant-design-vue](https://vue.ant.design/components/icon/).

**Comment by mrquokka** [comment]
> You need to write your own css animation.
> ant-design-icons does not contain styles.

Thanks, already do this. Looks like simple feature, but okay, i can do it  myself
