### ISSUE TITLE
Consider renaming exported names

### ISSUE THREAD

**Issue by DennisBaekgaard** [ant-design/ant-design-icons#152]
We are overall super happy with Ant-Design and are currently using the @alpha tag on v4. One thing we noticed though was that icons have been changed from `<Icon type="User" />` to `<User />`. This currently gives a whole bunch of clashes in declarations, e.g. if you have your own <User /> component. This risk only increases as more icons are added.

Currently we are aliasing everything so;

`import { User as UserIcon } from "..."`

Additionally the code becomes less readable because you cannot directly infer if <User /> is an icon component imported from antd, or if it's a proprietary component. This is for example the case between packages for `<Link />` which is also exported by React Router This is okay for sparsely used components, but seeing icons are used throughout an application this becomes a challenge. 

This is a worse developer experience compared to before. While I see the benefits from exporting each icon as their own component, have you considered pre or post-fixing them?

**Comment by vagusX** [comment]
We finally decide to use `Outlined` as suffix, so you can use Icon like this:

```tsx
import { UserOutlined, UserFilled, UserTwoTone } from '...'
```
