### ISSUE TITLE
@ant-design/icons-react-native部分配置需要更新

### ISSUE THREAD

**Issue by tourze** [ant-design/ant-design-icons#172]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - @ant-design/icons-react-native: https://npmjs.com/package/@ant-design/icons-react-native
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by BANG88** [comment]
@tourze 你是单独安装这个包的吗？

**Comment by suwu150** [comment]
我是单独安装到我的项目的package.json文件中，也有这样的提示！
<img width="490" alt="截屏2020-01-1511 17 35" src="https://user-images.githubusercontent.com/20339760/72402004-a44fe200-3788-11ea-973e-3daa3a387f1d.png">

提示内容如下所示：
<img width="998" alt="截屏2020-01-1511 18 33" src="https://user-images.githubusercontent.com/20339760/72402042-c6e1fb00-3788-11ea-8c07-0b83f675d306.png">

**Comment by suwu150** [comment]
我按照#172中的修改文件，确实是移除掉了警告，谢谢你

**Comment by zisheng-ai** [comment]
什么时候发布新版呢？

**Comment by zisheng-ai** [comment]
单独使用时，需要安装 babel-runtime

**Comment by zisheng-ai** [comment]
催更+1

**Comment by BANG88** [comment]
@youngjuning 2.0.0

**Comment by zisheng-ai** [comment]
@ant-design/react-native 依赖的图标名字错乱了，List.Item 的 arrow 属性全部显示错误

**Comment by Cupidor** [comment]
> @ant-design/react-native 依赖的图标名字错乱了，List.Item 的 arrow 属性全部显示错误

你好，我用Ant Design Mobile RN的时候图标也错乱了，List.Item 的 arrow 属性，复选框什么的都显示不出来，请问有解决的方法么，目前
@ant-design/icons-react-native": "^2.2.1
@ant-design/react-native": "^3.3.0
