### ISSUE TITLE
Huge bundle size without any explicit use, only of antd

### ISSUE THREAD

**Issue by itayganor** [ant-design/ant-design-icons#198]
Hi there.
In my project I use **antd** for components and **FontAwesome** for icons. I never explicitly use icons from Ant Design (Not a single `<Icon/>` component in my project).
Despite that, I can see that in my `bundle.js`, `@ant-design/icons` is about **0.5MB (!)** in size.

![image](https://user-images.githubusercontent.com/6430313/71318815-ba76c500-249e-11ea-84b7-ffbb1fa0313b.png)

In order to optimize antd imports, I use `babel-plugin-import` as such:
```json
["import", {
  "libraryName": "antd",
  "libraryDirectory": "es",
  "style": true
}]
```

But it doesn't seem to help with reducing the unused icons size taken in my bundle.

**Comment by patrickomeara** [comment]
I am also having this issue, we only use the table component but the whole library is included.

It's adding too much overhead. Is it possible to minimize this?

<img width="616" alt="image" src="https://user-images.githubusercontent.com/571773/72246857-cbeb6100-3647-11ea-99db-2605cf817c17.png">

**Comment by patrickomeara** [comment]
Looks like it's a major issue that is fixed in 4.0

https://github.com/ant-design/ant-design/issues/20661

**Comment by wzhudev** [comment]
Please refer to https://github.com/ant-design/ant-design/issues/12011.

**Comment by itayganor** [comment]
> Please refer to [ant-design/ant-design#12011](https://github.com/ant-design/ant-design/issues/12011).

It is all Chinese. It is not possible to refer people to texts they can't read.

**Comment by wzhudev** [comment]
@itayganor There are some comments in English. You can use some help from those, and Google Translate.

**Comment by nwoeddie** [comment]
[For future me and fellow Googlers...](https://github.com/ant-design/ant-design/issues/12011#issuecomment-623043192)
