### ISSUE TITLE
lerna publish 发布出去的 @ant-design/icons-react 是空的

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-icons#22]
<img width="352" alt="screen shot 2018-10-01 at 23 40 03" src="https://user-images.githubusercontent.com/465125/46299136-4c14c100-c5d3-11e8-8a96-8e1ab46951ab.png">

**Comment by wendzhue** [comment]
![default](https://user-images.githubusercontent.com/12122021/46300913-75375080-c5d7-11e8-8600-9905f21cbd79.PNG)

Works for me with 1.1.15. BTW, `@ant-design/icons-angular` seems not to be published with it.

**Comment by yesmeck** [comment]
是这个包 `@ant-design/icons-react`，刚刚发了一个 1.1.3，发现是空的，马上 unpublish 了。

因为这个包的 publish 命令是 `npm run pub` 而不是 `npm publish`。

**Comment by wzhudev** [comment]
@yesmeck 对我也注意到了...

**Comment by wzhudev** [comment]
@HeskeyBaozi 如果 angular 这边要和 icons, react 同步发布的话, 我需要做修改吗?

**Comment by HeskeyBaozi** [comment]
@yesmeck 
`@ant-design/icons-react` 的 `1.1.2` 我就是用 `lerna publish` 命令发布的。是没有在 lerna 工作目录下运行 `npm run react:compile` 编译文件？

@wendzhue 
`icons-angular` 直接依赖的是 `@ant-design/icons`，通常的变更就是图标的增删改 例如 https://github.com/ant-design/ant-design-icons/pull/21。
原则上，只要 `@ant-design/icons` 提供的接口有变化（例如图标的**减少**、`IconDefinition` 变化、helper函数的类型变化等），接口变化通常都非常谨慎且很少发生，此时各平台的适配器才需要检查发布。

**Comment by yesmeck** [comment]
如果 publish 前需要编译的话应该写到 `prepublish` 里。

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-react/package.json#L19

如果这个没用，也要删掉

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design-icons/pull/23
