### ISSUE TITLE
Attempted import error: 'AppstoreOutlined' is not exported from '@ant-design/icons'.

### ISSUE THREAD

**Issue by hsluoyz** [ant-design/ant-design-icons#229]
I found my React app encounters compile error these days. The code is OK two weeks ago. Did you change the `latest` pointer to another version without `AppstoreOutlined`?

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto

> web@0.1.0 start C:\xxx\web
> set PORT=6001 && react-scripts start
Starting the development server...
Failed to compile.

./src/TestPage.js
Attempted import error: 'AppstoreOutlined' is not exported from '@ant-design/icons'.

```

Some content of my `package.json`:

```
    "@ant-design/icons": "latest",
    "antd": "^4.0.0-rc.0",
```

**Comment by lavacake2019** [comment]
@ant-design/icons2.1.1 latest
4.0.0-alpha.15 alpha
4.0.0-rc.0 rc

**Comment by lavacake2019** [comment]
@ant-design/icons:    2.1.1 ----------- latest, 4.0.0-rc.0-------rc

**Comment by hsluoyz** [comment]
I used `4.0.0-rc.0` and it works.

**Comment by LuisRodriguezLD** [comment]
True, `4.0.0-rc.0` works but I don't think that's a reason for closing this issue 🤔.
After all, `rc0` is long gone

**Comment by marcosaguilera** [comment]
For all you looking for a solutions, it might works:

* Edit or add this on your `package.json` to `@ant-design/icons": "4.0.0-rc.0`
* Delete your node_modules folder
* run `npm i `or `npm install` this going to reinstall and recreate the icons dependency

Hope this helps anyone.
