### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-icons#26]
![image](https://user-images.githubusercontent.com/507615/46944346-5ee3c700-d0a4-11e8-8551-c75276223473.png)

**Comment by afc163** [comment]
<img width="66" alt="image" src="https://user-images.githubusercontent.com/507615/46944395-8044b300-d0a4-11e8-96d6-7a79bf292b2c.png">

这个也没有。

**Comment by wzhudev** [comment]
cross 也没有了, 现在全用 close 替代, 是故意要去掉 cross 吗?

**Comment by afc163** [comment]
@wendzhue 应该是bug，cross 替换为 close，也应该保留并向下兼容的。

**Comment by afc163** [comment]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/507615/47367722-d227b180-d712-11e8-96ba-f23d4aaf85c4.png">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9092

**Comment by afc163** [comment]
- [ ]  airplane: https://github.com/ant-design/ant-design/issues/12543

**Comment by afc163** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/507615/49135079-a3f44d80-f320-11e8-9f0d-148538665fc3.png">

**Comment by elhamsarikhani** [comment]
I am also missing the 'upload' icon which is available in the AntD documentation

**Comment by blue-lightning** [comment]
I want to request a banknote icon similar to this one [here.](https://www.iconfinder.com/icons/788355/banknote_currency_finance_money_yen_note_icon)

**Comment by afc163** [comment]
- [ ] linux: https://github.com/ant-design/ant-design/issues/14166

**Comment by zhengzhou1992** [comment]
Expectation: Kubernetes is a widely used brand, could you add it to "Brand and Logos" part?
[Kubernetes SVG logo](https://github.com/kubernetes/kubernetes/blob/master/logo/logo.svg)

**Comment by Sicria** [comment]
Discord would be a nice addition - https://discordapp.com/

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15850

**Comment by andreGarvin** [comment]
It seems like the more icon does not appear or is missing?
```javascript
<Icon type='more' />
```

**Comment by andreGarvin** [comment]
![Screen Shot 2019-06-17 at 3 11 28 AM](https://user-images.githubusercontent.com/15004253/59585274-1b67af80-90ae-11e9-9259-0e79a2640ae4.png)

**Comment by vishalshettydev** [comment]
any update on this issue? I am also not able to use many of the Icons that are listed in the antd document.

**Comment by cedricwang28** [comment]
[antd: Icon] Empty Icon

**Comment by genuineswe** [comment]
hello, any update?

**Comment by ShiftcodeDream** [comment]
Linux icon is still missing, and WE NEED IT !

**Comment by Argosax97** [comment]
Any news on adding the Linux icon ?
