### ISSUE TITLE
Attempted import error: 'xxxOutlined' is not exported from '@ant-design/icons'.

### ISSUE THREAD

**Issue by HowieHai** [ant-design/ant-design-icons#263]
Hi,

I just upgrade antD from v3 to v4. However, I found a small issue about the Icons. 

The screenshot shows below:

For example, I want to use "EditOutlined" Icon.

**In the official website, it is "EditOutlined":**
<img width="550" alt="Screen Shot 2020-03-21 at 6 40 12 PM" src="https://user-images.githubusercontent.com/18298737/77222023-82694600-6ba3-11ea-9f97-5db71b1997ca.png">
 
**In the code, it is "EditOutline":**
<img width="444" alt="Screen Shot 2020-03-21 at 6 43 00 PM" src="https://user-images.githubusercontent.com/18298737/77222050-d5db9400-6ba3-11ea-962a-01da6e212b62.png">

and, I have tested some of the icons that ended with "line" and "fill", which has this issue.

**Comment by latobibor** [comment]
I have the same issue with the added problem it does not even work. As per documentation I would need to just use `<EditOutline />`, however it is an `IconDefinition` object which I can't use: 
`JSX element type 'EditOutline' does not have any construct or call signatures.`

What step am I missing here?

**Comment by dongsongshan** [comment]
I have the same issue

**Comment by afc163** [comment]
```diff
- EditOutline
+ EditOutlined
```

**Comment by latobibor** [comment]
The problem got fixed by updating to `"antd": 4.0.4`. The `EditOutlined` icon was missing from exported members.

![image](https://user-images.githubusercontent.com/12050526/77555378-7937ec00-6eb7-11ea-8940-537e04300284.png)
