### ISSUE TITLE
Icon spin prop not working when custom

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design-icons#270]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-loading-icon-c80xk)

### Steps to reproduce
create svg icon
import antd Icon component
apply component prop with svg icon
apply spin prop

### What is expected?
icon to rotate on browser

### What is actually happening?
icon is not rotating

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome Version 80.0.3987.149 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
@vagusX , do we or should we support `spin` with customize icons?

**Comment by kosticfilip** [comment]
Maybe someone will find this usefull...
Was having the same issue, you need to spread props on svg, it needs to get class 'ant-spin' based on 'spin' prop.
https://codesandbox.io/s/antd-loading-icon-forked-hjpj5

**Comment by hugobarragon** [comment]
> be someone will find this usefull...
> Was having the same issue, you need to spread props on svg, it needs to get class 'an

Thanks, for me its a closed one then, it works, @zombieJ going to close this issue then, maybe add to documentation?
