### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by pradipta** [ant-design/ant-design-icons#291]
https://github.com/ant-design/ant-design-icons/blob/master/packages/icons

**Comment by wzhudev** [comment]
Try https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-svg.

**Comment by pradipta** [comment]
> Try https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-svg.

@wendellhu95 PR: https://github.com/ant-design/ant-design-icons/pull/292
