### ISSUE TITLE
webpack 4 problem

### ISSUE THREAD

**Issue by wulucxy** [ant-design/ant-design-icons#33]
after I upgrade to webpack 4，I have encounter one problem：

> actually I did not use this package。antd use it by default!

```javascript
TypeError: _iconsReact2.default.add is undefined
```

the reason is `_iconsReact2` is recognized as a commonjs version。

```javascript
// Initial setting
_iconsReact2['default'].add.apply(_iconsReact2['default'], (0, _toConsumableArray3['default'])(Object.keys(allIcons).map(function (key) {
    return allIcons[key];
})));
```

if I change to _iconsReact2['default']['default']，it will work，so，what is solution here?

**Comment by wulucxy** [comment]
finally i resolve this problem by add { "libraryDirectory": "es"} and {"modules": false}。
so please close this issue。3x

**Comment by afc163** [comment]
@wulucxy You can close it by youself.
