### ISSUE TITLE
react：typescript Error type

### ISSUE THREAD

**Issue by ghost** [ant-design/ant-design-icons#337]
类型 "{ className: string; onClick: () => undefined; }" 中缺少属性 "translate"，但类型 "Pick<AntdIconProps, "cite" | "data" | "form" | "label" | "span" | "style" | "summary" | "title" | "pattern" | "children" | "start" | "onClick" | "onSelect" | "defaultChecked" | ... 348 more ... | "twoToneColor">" 中需要该属性。

**Comment by lfpkkk** [comment]
Having exact same issue. Tried install @types/react and @types/react-dom to the project directly but doesn't seem to work.

**Comment by linuxonrails** [comment]
Same problem.
