### ISSUE TITLE
Error using @ant-design/icons with TypeScript

### ISSUE THREAD

**Issue by lfpkkk** [ant-design/ant-design-icons#354]
![image](https://user-images.githubusercontent.com/22840506/90587550-3e3ea800-e20c-11ea-96da-bfe91e7934e3.png)

Lately I have problem using icons with @ant-design/icons. It seems like this issue has been there for a while, but only a few people have encountered it.

I tried the solution @lukasluecke suggested in #304, which is to install @types/react and @types/react-dom directly to the project. But it does work for my situation. Any other suggestion on solving 

### package.json
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.29",
    "@fortawesome/free-solid-svg-icons": "^5.13.1",
    "@fortawesome/react-fontawesome": "^0.1.11",
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@pnp/common": "^2.0.6",
    "@pnp/graph": "^2.0.6",
    "@pnp/logging": "^2.0.6",
    "@pnp/odata": "^2.0.6",
    "@pnp/sp": "^2.0.6",
    "@pnp/telemetry-js": "^2.0.0",
    "@reduxjs/toolkit": "^1.4.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "antd": "^4.4.1",
    "office-ui-fabric-react": "6.189.2",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "react-highlight-words": "^0.16.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/rush-stack-compiler-3.7": "^0.5.2",
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.5",
    "ajv": "~5.2.2",
    "gulp": "^3.9.1"
  }
```

**Comment by linonetwo** [comment]
Same on me

```
Type '{ className: string; }' is missing the following properties from type 'Pick<AntdIconProps
```

**Comment by lfpkkk** [comment]
@chenshuai2144 @afc163 could you guys help me on this issue? have been struggling for weeks. I installed @types/react@16.9.49 and @types/react-dom@16.9.8 but doesn't work.

**Comment by lfpkkk** [comment]
@linonetwo After weeks of research, I finally noticed that @types/react and @types/react-dom are listed under devDependencies in package.json by default, but in my project they were moved under dependencies  somehow.
So my final solution to this issue is to move them back to devDependencies, of course with the latest version number, and then reinstall the whole node modules by npm intall.
![image](https://user-images.githubusercontent.com/22840506/91925959-bf1b9a80-ed08-11ea-9cad-917996564dfb.png)

Hope this is helpful for solving your issue as well.

**Comment by antstudio-git** [comment]
@lfpkkk  it doesn't work as followed your steps. I just use the icon with default props, but it warned.

is there any other ways to fix?

![image](https://user-images.githubusercontent.com/13619768/113657118-d58b3980-96cf-11eb-9135-9c6df477d36e.png)
![image](https://user-images.githubusercontent.com/13619768/113657312-49c5dd00-96d0-11eb-9cbd-d34255b82381.png)

**Comment by dexteryo** [comment]
Same issue. Any update on this?

**Comment by jiyarong** [comment]
same here

**Comment by Clarkkkk** [comment]
It may have something to do with the versions of @types/react and @types/react-dom. It works for me with @types/react@16.9.34 and @types/react-dom@16.9.6

**Comment by neonick** [comment]
Doesn't work with
````
"@types/react": "^17.0.0",
"@types/react-dom": "^17.0.0",
````

**Comment by sudarshan070** [comment]
Same issue with 
`
  "@types/react": "^16.9.53",
  "@types/react-dom": "^16.9.8",
`

**Comment by demigodliu** [comment]
Same Problem：
`"react": "^18.1.0"`   
`"react-dom": "^18.1.0"`

**Comment by eminoda** [comment]
https://github.com/ant-design/ant-design-icons/issues/483#issuecomment-1337294734

**Comment by Pankajsyal1** [comment]
<CaretRightOutlined rev={""}  rotate={isActive ? 90 : 0} />}>  add rev property it will fix

**Comment by PWbio** [comment]
```
"react": "17.0.2",
"react-dom": "17.0.2",
"@types/react": "17.0.65", // upgrade
"@types/react-dom": "17.0.20", // upgrade
"antd": "^5.9.0",
```

Upgrade types version works for me

**Comment by dizefurkan** [comment]
I have already upgrade versions but still get error

Check out my comment for details; screenshots
https://github.com/ant-design/ant-design-icons/issues/483#issuecomment-1779061345

**Comment by sohailamini** [comment]
Add these two:
`onPointerEnterCapture={undefined}
onPointerLeaveCapture={undefined}
`
![image](https://github.com/ant-design/ant-design-icons/assets/57681550/5b113d28-fdb2-46b7-9553-2ea69e4d9d0e)

**Comment by datawookie** [comment]
I was getting same error:

```
src/components/sidebar/sidebar.tsx:342:24 - error TS2739: Type '{}' is missing the following properties from
type 'Pick<AntdIconProps, "type" | "children" | "cite" | "data" | "form" | "label" | "slot" | "span" | "style"
| "summary" | "title" | "pattern" | "value" | "id" | "src" | ... 348 more ... | "twoToneColor">':
onPointerEnterCapture, onPointerLeaveCapture

342           expandIcon={<RightOutlined />}
```

and the solution from @sohail-amini worked for me!

**Comment by wctiger** [comment]
See https://github.com/ant-design/ant-design/issues/47886#issuecomment-1998979134
