### ISSUE TITLE
useInsertStyles hook is braking Content Security Policy

### ISSUE THREAD

**Issue by sebadlf** [ant-design/ant-design-icons#377]
The [Icon](https://github.com/ant-design/ant-design-icons/blob/9393e3ed72de5bf67546b615f382394e140be79b/packages/icons-react/src/components/Icon.tsx) component is calling the hook [useInsertStyles](https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-react/src/utils.ts).

Then useInsertStyles uses insertCss which doesn't knows anything about the CSP used in Ant Design 4

```javascript
export const useInsertStyles = (styleStr: string = iconStyles) => {
  useEffect(() => {
    if (!cssInjectedFlag) {
      insertCss(styleStr, {
        prepend: true,
      });
      cssInjectedFlag = true;
    }
  }, []);
};
```

Up to my knowledge insertCss doesn't support a Content Security Policy 

Regards

**Comment by cross13** [comment]
There is any update about this issue ? :)

**Comment by EMichaelC** [comment]
Has this issue been fixed? Setting a nonce via the ConfigProvider is still not working.

**Comment by badams** [comment]
@zombieJ @EMichaelC Not working for me on `@ant-design/icons@4.6.3` & `antd@4.16.13`
