### ISSUE TITLE
default Icon theme is missing in react and vue adaptors

### ISSUE THREAD

**Issue by hongchanhk01** [ant-design/ant-design-icons#41]
Hello!
I am trying to build some components libs on top of ant-design for internal usages.

Included the the ant-design as dependencies and use `rollup` to bundle it up.

After that I start a `create-react-app` application and test it out for my components libs.

And getting this errors:

![image](https://user-images.githubusercontent.com/44665484/50329142-d57fc380-0530-11e9-8081-afa9080febff.png)

It seem the angular adaptor will passing the default theme when then `theme` is `undefined`

https://github.com/ant-design/ant-design-icons/blob/f8cac49b8ce9909e222a16202fdf6014cdd1dc13/packages/icons-angular/lib/component/icon.directive.ts#L69

but seem the vue and react did not share the same behaviour

https://github.com/ant-design/ant-design-icons/blob/9ba5f3fdc1d6bf7011cbb28e48e53d164c33b6d1/packages/icons-react/src/components/Icon.tsx#L40

https://github.com/ant-design/ant-design-icons/blob/ccfc791bf175801e5fd28e23f37345d596f0780b/packages/icons-vue/src/components/Icon.jsx#L27

Maybe we should unify the this behaviour across different platform

**Comment by wzhudev** [comment]
@hongchanhk01 

Hi. I am the author of the Angular adapter. You quoted a wrong line of the code. Actually, it's:

https://github.com/ant-design/ant-design-icons/blob/f8cac49b8ce9909e222a16202fdf6014cdd1dc13/packages/icons-angular/lib/component/icon.service.ts#L86

For icons provided by ant design, `theme` property should always be specified.

So I guess the problem wasn't because of these codes?

**Comment by hongchanhk01** [comment]
@wendzhue 

Indeed, I try to dig a little bit deeper seem the data from Icons not that correct. Not sure is it my build problem or something else

![image](https://user-images.githubusercontent.com/44665484/50331421-88ecb600-0539-11e9-97ba-57354e4e746f.png)

You can see there are some incorrect data at the first two item for the icons array

**Comment by wzhudev** [comment]
@hongchanhk01 I guess something is wrong with your building process. Actually, you just have to add raw svg files under `svg` dir and our script would do everything for you.

**Comment by hongchanhk01** [comment]
@wendzhue 

I do think so. Thank you for your time and sorry for the noise.

It seem `rollup` include `default` es export for `allIcons`. 

![image](https://user-images.githubusercontent.com/44665484/50332324-b9821f00-053c-11e9-8b49-93995336081f.png)

Will close the issues for now.

**Comment by hongchanhk01** [comment]
@wendzhue 

Sorry for bother u again

https://github.com/ant-design/ant-design/blob/af8a025aebba01b28ff04fecff76d30117b6e068/components/icon/index.tsx#L3

https://github.com/ant-design/ant-design/commit/c76a90b2b78b07364361c7b20e6703ca2eecf5c1

May I know shouldn't the import here for ant design icon using just `@ant-design/icons` instead of the  `@ant-design/icons/lib/dist` build.

Maybe this is why rollup does pick up the correct es modules ?

**Comment by Torone** [comment]
@hongchanhk01 Can I know how did you fix the rollup configuratiuon to avoid this annoying issue? Thanks

**Comment by htmlin** [comment]
@hongchanhk01 Can I know how did you fix the rollup configuratiuon to avoid this annoying issue? Thanks
