### ISSUE TITLE
@ant-design/icons@4.6.2 使用图标时提示报错

### ISSUE THREAD

**Issue by six006** [ant-design/ant-design-icons#483]
在使用图标时，

`import { MenuUnfoldOutlined } from '@ant-design/icons';<MenuUnfoldOutlined />`

报下面的错误，换成4.0.0就没有问题了，怎么解决呢？

Type '{}' is missing the following properties from type 'Pick<AntdIconProps, "name" | "className" | "style" | "cite" | "data" | "form" | "label" | "slot" | "span" | "summary" | "title" | "pattern" | "children" | "id" | "size" | ... 347 more ... | "twoToneColor">': name, className, style, cite, and 356 more.  TS2740

**Comment by afc163** [comment]
升级 @types/react 和 TS 版本。

**Comment by eminoda** [comment]
[4.3.0](https://www.npmjs.com/package/@ant-design/icons/v/4.3.0) 可以试试

**Comment by whinc** [comment]
@types/react@17.0.0 升级到 @types/react@17.0.65 后，问题解决

**Comment by dizefurkan** [comment]
> 升级 @types/react 和 TS 版本。

I have already upgrade @types/react version but error is still there 
<img width="743" alt="Screenshot 2023-10-25 at 14 28 22" src="https://github.com/ant-design/ant-design-icons/assets/28892291/b5edc54b-baa7-462b-a540-9e1bce7d1263">
<img width="683" alt="Screenshot 2023-10-25 at 14 28 37" src="https://github.com/ant-design/ant-design-icons/assets/28892291/f7781c01-785a-4bf0-bde2-98d82d381e06">
<img width="369" alt="Screenshot 2023-10-25 at 14 29 16" src="https://github.com/ant-design/ant-design-icons/assets/28892291/b4255f29-0225-43dc-9cc1-71a979770f3e">

**Comment by Yung-Sun** [comment]
> > 升级 @types/react 和 TS 版本。
> 
> I have already upgrade @types/react version but error is still there <img alt="Screenshot 2023-10-25 at 14 28 22" width="743" src="https://user-images.githubusercontent.com/28892291/277989364-b5edc54b-baa7-462b-a540-9e1bce7d1263.png"> <img alt="Screenshot 2023-10-25 at 14 28 37" width="683" src="https://user-images.githubusercontent.com/28892291/277989380-f7781c01-785a-4bf0-bde2-98d82d381e06.png"> <img alt="Screenshot 2023-10-25 at 14 29 16" width="369" src="https://user-images.githubusercontent.com/28892291/277989522-b4255f29-0225-43dc-9cc1-71a979770f3e.png">

@dizefurkan You can try downgrading to version 4.3.0 [@ant-design/icons@4.3.0]. It works for me :)

**Comment by cwy007** [comment]
```
-    "@ant-design/icons": "4.8.1"
+    "@ant-design/icons": "4.8.2"
```
