### ISSUE TITLE
@ant-design/icons v4.6.3webpack打包tree-shaking失效

### ISSUE THREAD

**Issue by alienzhangyw** [ant-design/ant-design-icons#486]
原来是4.3版本，今天更新了一下最新版本，结果除了用到的十几个图标，index.js也全部都打包进去了。现在icons成为我项目体积最大的包……
![image](https://user-images.githubusercontent.com/58874541/121662465-f5781880-cad7-11eb-8c8d-4d07daac28d2.png)

我用的neutrino，babel配置如下：
![image](https://user-images.githubusercontent.com/58874541/121664568-2eb18800-cada-11eb-88d9-6ea583508641.png)

**Comment by careyke** [comment]
遇到了同样的问题

**Comment by alienzhangyw** [comment]
移除了babel-plugin-import的使用后解决了。记得导入antd的css。

**Comment by careyke** [comment]
> 移除了babel-plugin-import的使用后解决了。记得导入antd的css。

这样做是不是会把所有组件的css文件都导入了，导致css文件比较大

**Comment by alienzhangyw** [comment]
> > 移除了babel-plugin-import的使用后解决了。记得导入antd的css。
> 
> 这样做是不是会把所有组件的css文件都导入了，导致css文件比较大

我的项目基本上用到了所有组件，所以影响不大。而且最新版antd我发现使用babel-plugin-import，设置style: true会导致所有antd的css都不加载。 

如果你在意css大小的话可以尝试这个https://www.npmjs.com/package/@shaking/antd-css 不过我没试过。
