### ISSUE TITLE
Feature Request: Commit

### ISSUE THREAD

**Issue by lchrennew** [ant-design/ant-design-icons#487]
现在已经有了Branch、Fork、PullRequest，希望再来个Commit

**Comment by afc163** [comment]
Commit 预期长什么样。

**Comment by lchrennew** [comment]
![image](https://user-images.githubusercontent.com/1522365/122860154-cd967980-d34f-11eb-9a58-5b68c18938fc.png)
类似这个样

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/issues/71#issuecomment-867302684
