### ISSUE TITLE
Update TypeScript peer dependency

### ISSUE THREAD

**Issue by krokofant** [ant-design/ant-design-icons#50]
The current stable 7.x release of NgZorro uses TypeScript "~3.2.2" while the angular-icons uses "~3.1.3".

Could these be synced up so that npm won't warn about mismatching peer dependencies?

**Comment by wzhudev** [comment]
@krokofant angular-icons uses TypeScript@3.1.3 mostly because I use Windows and TypeScript@3.2.2 breaks on Windows! 🤣  See: https://github.com/Microsoft/TypeScript/issues/29221

I think this wouldn't break anything, currently?

**Comment by krokofant** [comment]
@wendzhue Thanks for the note. The updated TypeScript version is what broke our build while upgrading ant 😄 I'm sure it's fine
