### ISSUE TITLE
[Feature Request]: Angular 16 support

### ISSUE THREAD

**Issue by youssef3wi** [ant-design/ant-design-icons#565]
The [ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd) requires [ant-design-icons](https://github.com/ant-design/ant-design-icons) as a dependency, but it is not compatible with Angular 16.

**Comment by slodobane** [comment]
Hi,
the same problem here.

**Comment by Nicoss54** [comment]
Hey is it possible to make a beta release of this library ? This is the last bullet point for completely migrate the Ng-Zorro library.

Thanks for all the work you did

**Comment by jornare** [comment]
https://www.npmjs.com/package/@ant-design/icons-angular?activeTab=versions
v16 beta.0 is out

**Comment by StefanNedelchev** [comment]
@youssef3wi  There is an official  16.0.0 release of the package so this might be closed
