### ISSUE TITLE
icons-angular release 2.0.3

### ISSUE THREAD

**Issue by EnzDev** [ant-design/ant-design-icons#57]
Hello,
Yesterday, I've upgraded my package.json with `@ant-design/icons-angular@2.0.3`, today I'm unable to deploy my code because you removed the `2.0.3` release and pushed the `2.0.4` one.
Is there a specific reason to remove this release from npmjs? Removing a release (instead of marking it as deprecated) can lead to many problems and I do not understand this choice.

**Comment by wzhudev** [comment]
@EnzDev That version doesn't contain folder `src/inline-svg`. So we have to unpublish it in case someone uses the invalid version. Sorry for the inconvenience.
