### ISSUE TITLE
5.1.1 版本构建出的 UMD 模块报错，找不到 React

### ISSUE THREAD

**Issue by ShenHongFei** [ant-design/ant-design-icons#574]
5.1.0 正常
升级到 5.1.1 之后出现

Uncaught TypeError: Cannot read properties of undefined (reading 'createContext')
    at icons.min.js:1:695124
    at icons.min.js:1:795911
    at icons.min.js:1:795916
    at icons.min.js:1:247
    at icons.min.js:1:329

![image](https://github.com/ant-design/ant-design-icons/assets/15074472/e56d5072-eacf-405b-a2a7-893c827e98d0)

可能的原因是
window 上取不到 window.React 属性，应该直接取 React 属性
![image](https://github.com/ant-design/ant-design-icons/assets/15074472/e3f6d23c-60c2-410a-9f49-ade182b53e03)

**Comment by zombieJ** [comment]
搞个重现看看？我 Debug 一下~

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design-icons/pull/573/files#diff-c57dba5b5e9d091e853c615d28ab7e34c12efc1302a862cf6ecbd22d8fb75a10R10  @PeachScript  看一下是不是配置不兼容

**Comment by PeachScript** [comment]
> https://github.com/ant-design/ant-design-icons/pull/573/files#diff-c57dba5b5e9d091e853c615d28ab7e34c12efc1302a862cf6ecbd22d8fb75a10R10 @PeachScript 看一下是不是配置不兼容

应该是的，externals 配置需要省略 `window`，旧版基于 Rollup，新版基于 Webpack

**Comment by abearxiong** [comment]
哈哈哈哈哈，5.1之后都是问题

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design-icons/commit/49a8c618c3bed3d85115f3eafe349e74ca984bf0

**Comment by afc163** [comment]
@zombieJ 请发 PR

**Comment by ShenHongFei** [comment]
### 5.1.2 版本修复了找不到 React 的报错，但还是没有 icons 全局变量，似乎所有的导出都放到了 window 上
![image](https://github.com/ant-design/ant-design-icons/assets/15074472/0184bb29-f54c-4c82-ba97-b57a7d320392)

### webpack 中 externals 配置如下
![image](https://github.com/ant-design/ant-design-icons/assets/15074472/c87fad87-4b2d-4ec1-abd5-89af1db88b92)

@PeachScript @afc163

**Comment by afc163** [comment]
这个问题疑似还在。

**Comment by PeachScript** [comment]
> 这个问题疑似还在。

问题有复现吗
