### ISSUE TITLE
Chrome console: Unknown DOM property fill-rule. Did you mean fillRule?

### ISSUE THREAD

**Issue by gexin1** [ant-design/ant-design-icons#587]
Seems like JSX error.
We should convert the svg attribute "fill rule" to "fillRule"
doc https://facebook.github.io/react/docs/dom-elements.html#all-supported-svg-attributes

**Comment by yookue** [comment]
+1
8.1 号发布的 @ant-design/icons-svg@4.3.0 有问题，锁版本到 4.2.1 就好了

**Comment by davidhsing** [comment]
+1
8.1 号发布的 @ant-design/icons-svg@4.3.0 有问题，锁版本到 4.2.1 就好了

**Comment by pluveto** [comment]
Same issue

**Comment by afgcsborges** [comment]
Same issue, temporary fix is to add to resolutions on package.json:
"resolutions": {
        "@ant-design/icons-svg": "4.2.1"
    },
