### ISSUE TITLE
@ant-design/icons  导出的图标ts 类型为啥rev是必填 

### ISSUE THREAD

**Issue by Jerryqun** [ant-design/ant-design-icons#593]
![image](https://github.com/ant-design/ant-design-icons/assets/26621285/7527bfe9-0e6c-4db4-b1cf-40ecfbdffd70)
![image](https://github.com/ant-design/ant-design-icons/assets/26621285/49314d64-8b30-4029-ac54-5ed4dc2be6df)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/issues/483#issuecomment-863766986

**Comment by dizefurkan** [comment]
> [#483 (comment)](https://github.com/ant-design/ant-design-icons/issues/483#issuecomment-863766986)

This does not works for me. Check out my comment ->
https://github.com/ant-design/ant-design-icons/issues/483#issuecomment-1779061345
