### ISSUE TITLE
Replace unicode characters with Icon component in antd

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-icons#6]
Some components reference icons by unicode character in CSS directly, [example](https://github.com/ant-design/ant-design/blob/96d8fc45f1f1d0b6cf979e6aedcd3e700849126c/components/select/style/index.less#L30). We should replace these unicode characters by `Icon` component.

**Comment by HeskeyBaozi** [comment]
## Todos
---

- [x] Cascader 级联选择 

https://github.com/react-component/cascader/pull/30

<img width="50%" src="https://user-images.githubusercontent.com/15819224/43055954-f824c7fa-8e6b-11e8-8eba-4c66871ac523.png" />

---

- [x] DatePicker 日期选择

https://github.com/react-component/calendar/pull/405
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43056685-2a641d70-8e70-11e8-9102-30843ec8cd5e.png" />
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43057037-3cc431c4-8e72-11e8-8f0b-c92fb6fcf44c.png" />

---

- [x] Collapse 折叠面板

https://github.com/react-component/collapse/pull/89
![image](https://user-images.githubusercontent.com/15819224/43115946-1ff0af3e-8f38-11e8-802a-376a2499ace6.png)
---

- [ ] Drawer 抽屉

![image](https://user-images.githubusercontent.com/15819224/43122941-54a80b42-8f55-11e8-915a-f1f3623d3c1c.png)
---

- [x] Dropdown 下拉菜单

https://github.com/react-component/menu/pull/182

<img width="50%" src="https://user-images.githubusercontent.com/15819224/43123937-43d56014-8f58-11e8-9282-a473c4cedc97.png" />

---

- [ ] Form 表单验证

<img width="50%" src="https://user-images.githubusercontent.com/15819224/43185365-4f55a996-901e-11e8-8637-1d3c37a24e25.png" />


---

- [ ] InputNumber 数字选择器

<img width="50%" src="https://user-images.githubusercontent.com/15819224/43185319-23cb0460-901e-11e8-8aca-76c0e0e690ac.png" />

---

- [x] Modal 模态框

https://github.com/react-component/dialog/pull/89
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43194882-11cc0cc4-9036-11e8-91ba-015682f2ba3f.png" />

---

- [x] Notification 通知栏

https://github.com/react-component/notification/pull/45
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43252860-1b1f6b52-90f6-11e8-82b6-e7659daf23a8.png" />

---

- [ ] Pagination 分页

https://github.com/react-component/pagination/pull/139
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43256230-b41adb40-90fe-11e8-979a-f162e6a6d0aa.png" />

---

- [x] Select 选择器

https://github.com/react-component/select/pull/314
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43113970-30d0060a-8f2f-11e8-83fc-5af0d37cf852.png" />
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43113872-d691ff68-8f2e-11e8-8f1a-af2c14cb9084.png" />

---

- [x] Switch 开关

https://github.com/react-component/switch/pull/23
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43299269-22e65ab2-918c-11e8-9c93-7ee390ced499.png" />

---

- [x] Tabs 标签页

https://github.com/react-component/tabs/pull/131
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43305599-f6e85946-91aa-11e8-9d1d-6ed1d7efb179.png" />
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43305620-0bbc166e-91ab-11e8-99cd-4d58a541bd78.png" />

---

- [x] TimePicker 时间选择器

https://github.com/react-component/time-picker/pull/114
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43186404-236501c6-9021-11e8-822e-274ab3595f20.png" />
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43186416-2f4c0796-9021-11e8-8d79-02af960e5ea6.png" />

---

- [x] TreeSelect 树选择器

https://github.com/react-component/tree/pull/182
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43384699-5fd33aee-9411-11e8-97e9-2e7dc3f4291e.png" />
<img width="50%" src="https://user-images.githubusercontent.com/15819224/43384738-7c124c22-9411-11e8-85c5-0452f02a6269.png" />
