### ISSUE TITLE
[Angular] Allow usage with trusted types

### ISSUE THREAD

**Issue by timonmasberg** [ant-design/ant-design-icons#614]
Currently, when using CSP with trusted types, an error will be thrown, since the `IconService` uses [`innerHTML`](https://github.com/ant-design/ant-design-icons/blob/d7c5ad5015a0cbb67c4c1faa639edc1c4d16c23a/packages/icons-angular/src/component/icon.service.ts#L350). I propose a function for optional registering of a trusted policy to allow using trusted types.

**Comment by timonmasberg** [comment]
you can utilize the default policy for this

**Comment by acomito** [comment]
@timonmasberg Can you clarify? You set require-trusted-types-for to default?

**Comment by timonmasberg** [comment]
> require-trusted-types-for to default?

No, you can create a policy for "default", which allows you to sanitize the `innerHTML` calls from the `IconService`.
