### ISSUE TITLE
@types/react 18.2.66版本删除了onPointerEnterCapture、onPointerLeaveCapture事件

### ISSUE THREAD

**Issue by caocong1** [ant-design/ant-design-icons#628]
这是@types/react的pull链接[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68984](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68984)

会导致报ts错误：
error TS2739: Type '{}' is missing the following properties from type 'Pick<AntdIconProps, "title" | "name" | "color" | "size" | "start" | "children" | "style" | "type" | "rowSpan" | "cite" | "data" | "form" | "label" | "slot" | "span" | ... 348 more ... | "twoToneColor">': onPointerEnterCapture, onPointerLeaveCapture

**Comment by little-time** [comment]
我也出现了，怎么解决的

**Comment by coder-zhuzm** [comment]
upup

**Comment by sinna94** [comment]
I temporarily resolved this by setting @types/react to version 18.2.65 until the issue was resolved.

**Comment by vagusX** [comment]
Fixed in @ant-design/icons@5.3.2

**Comment by qld-cf** [comment]
> Fixed in @ant-design/icons@5.3.2

@vagusX  4.x版本会有修吗

**Comment by zmq3821** [comment]
> 我也出现了，怎么解决的

我升级icon的版本解决了这个问题，"@ant-design/icons": "^5.3.4"

**Comment by zmq3821** [comment]
我升级icon的版本解决了这个问题，"@ant-design/icons": "^5.3.4"
