### ISSUE TITLE
@ant-design/icons@4.8.1 tsc 失败

### ISSUE THREAD

**Issue by keiseiTi** [ant-design/ant-design-icons#630]
看到主干分支已经修复了，但 @ant-design/icons@4.8.1  存在这个问题
<img width="967" alt="image" src="https://github.com/ant-design/ant-design-icons/assets/28672197/f9ccbb0e-c128-4b00-85c7-a66f0f1961c8">

![image](https://github.com/ant-design/ant-design-icons/assets/28672197/48d97c49-6555-42d6-b6b3-7dd55bdb4168)

![image](https://github.com/ant-design/ant-design-icons/assets/28672197/69cc1539-1b34-40bb-bc16-e57430133cc9)

**Comment by qld-cf** [comment]
+1

**Comment by wzc520pyfm** [comment]
@vagusX

**Comment by wzc520pyfm** [comment]
@vagusX Will there be an update to version 4.x? Because @types/react also relased version 17.0.78, @ant-desgin/[icon@4.x](mailto:icon@4.x) will also report this error.

**Comment by wzc520pyfm** [comment]
https://github.com/ant-design/ant-design-icons/pull/631

**Comment by Thulof** [comment]
> @vagusX Will there be an update to version 4.x? Because @types/react also relased version 17.0.78, @ant-desgin/[icon@4.x](mailto:icon@4.x) will also report this error.

You can temporarily fix it by pinning the version of `@types/react` to 17.0.76 or 18.2.65 using resolutions field in package.json.

I have suggested that they (maintainer of `@types/react`) roll back and release a fixed version. https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69006

Update:
New version package of @types/react is published. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69005 
Update @types/react will resolve this issue.
