### ISSUE TITLE
latest tag 指向的是 4.x 版本

### ISSUE THREAD

**Issue by hellohejinyu** [ant-design/ant-design-icons#634]
![图片](https://github.com/ant-design/ant-design-icons/assets/8766034/6985a659-22d5-40c0-88bb-5c76486b9630)

导致直接安装的话，会安装 4.x 版本

**Comment by redraiment** [comment]
+1 升级的时候版本反而降级了

**Comment by MadCcc** [comment]
已指回 v5.3.4

**Comment by millerhamburger** [comment]
真的绝了0.0

**Comment by millerhamburger** [comment]
我还以为我们公司的镜像有问题
