### ISSUE TITLE
latest tag 再次指向了 4.x 版本

### ISSUE THREAD

**Issue by redraiment** [ant-design/ant-design-icons#637]
#634 这个issue已经close了，但昨天发布了5.3.5之后，latest再次被指向了4.x版本。

![Screenshot_20240323_101109](https://github.com/ant-design/ant-design-icons/assets/932074/b7d3e608-11cb-40e1-8592-92b2d808ff45)

**Comment by andyyxw** [comment]
![image](https://github.com/ant-design/ant-design-icons/assets/41931722/7bc29b88-0732-4b2f-9cd4-b187367b2536)
对啊，插件都凌乱了
