### ISSUE TITLE
 [vite] Internal server error: [vite] Named export 'UserOutlined' not found. The requested module '@ant-design/icons' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by Liian123** [ant-design/ant-design-icons#652]
当我在vite 5.1.0 和remix2 中使用时，导入图标组件会报错，以下是报错信息；当使用"@ant-design/icons": "5.1.4" 版本则没问题。

[vite] Named export 'UserOutlined' not found. The requested module '@ant-design/icons' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@ant-design/icons';
const {UserOutlined} = pkg;

项目地址 https://github.com/Liian123/my-remix-app

急急急

**Comment by afc163** [comment]
Fixed in `@ant-design/icons@5.4.0`: https://github.com/ant-design/ant-design-icons/pull/653
