### ISSUE TITLE
5.5版本的icon去掉了fill currentColor 导致antd createFromIconfontCN方式使用图标时 颜色显示不对

### ISSUE THREAD

**Issue by ljmCoder** [ant-design/ant-design-icons#671]
![image](https://github.com/user-attachments/assets/9b24109f-e6f1-4e8d-bf88-e47d23e1f741)

**Comment by anxLiang** [comment]
+1

**Comment by ljmCoder** [comment]
@afc163 能帮忙看看吗

**Comment by anxLiang** [comment]
您的来件我已收到，我会尽快处理。

**Comment by ljmCoder** [comment]
@afc163

**Comment by afc163** [comment]
Reproduce: https://stackblitz.com/edit/vitejs-vite-laj1ei?file=src%2FApp.tsx

**Comment by GuanJdoJ** [comment]
为啥关闭了，使用 createFromIconfontCN 的图标该如何配置才能使 svg 具有初始属性 fill="currentColor"，现在已经导致自定义图标在Button中无法 inherit color了。
<img width="97" alt="image" src="https://github.com/user-attachments/assets/3c871fad-7a79-4979-8d74-2958f4f38b7b">

**Comment by afc163** [comment]
￼
![image](https://github.com/user-attachments/assets/7628c1c3-1677-43cc-bc89-014ec3deb3ac)


@GuanJdoJ 看下这里。

**Comment by GuanJdoJ** [comment]
我知道了，我刚才点进去有一个 PR 还是 open 状态，不知道处理完了没有，现在把`@ant-design/icons`升级到 5.5.1 就解决了
