### ISSUE TITLE
Vue how to use the filled icon？

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design-icons#70]
1. Versions: 
  - "@ant-design/icons": "^2.1.1",
   - "@ant-design/icons-vue": "^2.0.0",

2. Usage:

```js
import Vue from 'vue'
import {
  DashboardOutline,
  CheckCircleFill,
  CheckCircleOutline,
  CloseCircleFill,
  CloseCircleOutline,
  InfoCircleFill
} from '@ant-design/icons'
import AntdIcon from '@ant-design/icons-vue'

console.log('AntdIcon: ', CheckCircleOutline)
AntdIcon.add(
  DashboardOutline,
  CheckCircleFill,
  CheckCircleOutline,
  CloseCircleFill,
  CloseCircleOutline,
  InfoCircleFill
)
Vue.use(AntdIcon)
```

```js
 render () {
   return (<antd-icon class="success" type="check-circle"></antd-icon>)
}
```

3. Actual effect

`Nothing is rendered`

4.  Expectation

![image](https://user-images.githubusercontent.com/8147202/61525500-24e88c80-aa4b-11e9-8dd2-3eb4328cea81.png)

**Comment by wzhudev** [comment]
Why don't you read the doc?

<img width="1037" alt="屏幕快照 2019-07-19 下午5 36 39" src="https://user-images.githubusercontent.com/12122021/61525848-d091dc80-aa4b-11e9-8bad-4d6ab3264242.png">

**Comment by fengyun2** [comment]
@wendzhue Please review. I just use `@ant-design/icons` and `@ant-design/icons-vue` instead of `ant-design-vue`.

**Comment by tangjinzhou** [comment]
@fengyun2 直接使用不是很方便，你可以参考 `ant-design-vue` 进行二次开发
 https://github.com/vueComponent/ant-design-vue/blob/master/components/icon/index.js#L102

**Comment by fengyun2** [comment]
我们前端UI框架选了Element UI，但是看到 `@ant-design/icons` 的图标比较多和我们刚好需要这些图标，就看下能不能用而已，再引入 `ant-design-vue` 就有点庞大了。
