### ISSUE TITLE
图标命名有误：check-close-circle 或应为 check-circle

### ISSUE THREAD

**Issue by fjc0k** [ant-design/ant-design-icons#9]
`check-close-circle` 或应为 `check-circle`。

链接：https://github.com/ant-design/ant-design-icons/blob/dev/src/svg/check-close-circle.svg

另外，不考虑将 svg 图标发布上 npm 吗？

**Comment by HeskeyBaozi** [comment]
目前图标和文档中的图标命名是不一致的，现在的图标命名尚不遵循图标命名规范，不建议在生产环境中使用。
已经发布在`npm`上。
```bash
yarn add @ant-design/icons
```

**Comment by fjc0k** [comment]
@HeskeyBaozi ok，不过我这儿说的是 `src/svg` 下的图标应该发布去 npm，package.json 的 `files` 应该加上 `src`：

```json
  "files": [
    "es",
    "lib",
    "README.md",
    "src"
  ],
```

目前 npm 上无 svg 源文件：https://unpkg.com/@ant-design/icons/

**Comment by HeskeyBaozi** [comment]
用户直接消费的是`lib`和`es`中的已经结构化的图标数据结构。
发布`svg`会造成冗余。

**Comment by fjc0k** [comment]
@HeskeyBaozi 特定结构的数据对使用的工具有要求吧。而 svg 源文件，可满足各式需求。

**Comment by HeskeyBaozi** [comment]
的确。这种需求也是有的。

**Comment by HeskeyBaozi** [comment]
474f817f4cc69481591204e13c9b6bdda1bd417b
https://unpkg.com/@ant-design/icons/

**Comment by fjc0k** [comment]
@HeskeyBaozi ok，还有个建议：发布的 svg 文件名可考虑统一小写，再把空格转为 `-` 号。如此，可使用 babel-plugin-import 进行按需加载：

```js
  plugins: [
    ['import', {
      libraryName: '@ant-design/icons',
      customName: name => `@ant-design/icons/svg/${name}.svg`
    }, 'ant-design-icons']
  ]
```
